dataset:
  path: "data/processed/mmasd_features.csv"
  target: "label"

model:
  type: "xgboost"
  params:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8

output:
  model_path: "artifacts/model.pkl"
  metrics_path: "artifacts/metrics.csv"
